{% set name = "empanada-dl" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/empanada-dl-{{ version }}.tar.gz
  sha256: 4289e69842242203be77cdb656a12fb2be4ed83816969b24a0b4eab1d67c3b91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - albumentations >=1.2
    - connected-components-3d >=3.10
    - cztile
    - dask-core >=2022.5.2
    - imagecodecs
    - matplotlib-base
    - numba >=0.54
    - numpy >=1.20
    - opencv >=4.5.3
    - python >=3.7
    - pyyaml
    - scikit-image >=0.19
    - pytorch >=1.10
    - torchvision >=0.2
    - zarr >=2.12

test:
  imports:
    - empanada
  commands:
    - pip list
    # - pip check  # because opencv-python
  requires:
    - pip

about:
  home: https://github.com/volume-em/empanada
  summary: Algorithms for Panoptic Segmentation of organelles in EM
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
